### ISSUE TITLE
Procedural macro `rental!` relies on deprecated crate

### ISSUE THREAD

**Issue by davish** [markbenvenuto/mrlog#4]
I've previously compiled `mrlog` without any problem with `rustc 1.56.0`, but when compiling with `rustc 1.58.0`, I got this error:
```
error: using `procedural-masquerade` crate
  --> src/main.rs:62:1
   |
62 | / rental! {
63 | |     pub mod rent_object {
64 | |         use std::rc::Rc;
65 | |
...  |
72 | |     }
73 | | }
   | |_^
   |
   = note: `#[deny(proc_macro_back_compat)]` on by default
   = warning: this was previously accepted by the compiler but is being phased out; it will become a hard error in a future release!
   = note: for more information, see issue #83125 <https://github.com/rust-lang/rust/issues/83125>
   = note: The `procedural-masquerade` crate has been unnecessary since Rust 1.30.0. Versions of this crate below 0.1.7 will eventually stop compiling.
   = note: this error originates in the macro `rental` (in Nightly builds, run with -Z macro-backtrace for more info)

error: could not compile `mrlog` due to previous error
```

It seems like the [rental crate](https://crates.io/crates/rental) is no longer maintained so I would doubt that a fix will be published to that crate, but for now you can still compile by ignoring this specific warning:
```
RUSTFLAGS="$RUSTFLAGS -A proc_macro_back_compat" cargo build --release
```

**Comment by markbenvenuto** [comment]
@davish Thanks for the report. Since it no longer compiles cleanly with `rental`, I will finally make the switch to https://github.com/joshua-maros/ouroboros which is similar and does compile cleanly with `1.58`.

I quickly prototyped it and it appears to work. I will likely push and update tomorrow or early next week after I finish testing.

**Comment by markbenvenuto** [comment]
Pushed a new update with https://github.com/markbenvenuto/mrlog/commit/531ae676b77a6e5760038d0c24afe319aa0c7d2a that compiles with Rust 1.58. cleanly.
