### ISSUE TITLE
Build broken in Linux

### ISSUE THREAD

**Issue by dgomezferro** [markbenvenuto/mrlog#5]
Commit 531ae676b77a6e5760038d0c24afe319aa0c7d2a breaks the build on Linux:

```
$ cargo build --release
   Compiling mrlog v0.2.1 (/home/ubuntu/mrlog)
error: Unsupported attribute
  --> src/main.rs:75:3
   |
75 | #[cfg(target_os = "linux")]
   |   ^^^
```

Reverting 531ae676b77a6e5760038d0c24afe319aa0c7d2a works. It looks like the `cfg` attribute is not compatible with `#[self_referencing]`

**Comment by markbenvenuto** [comment]
Yes. The `cfg` tag could not be placed there yet it somehow allowed me to compile on Windows. I fixed both Linux and Windows with 18deac15b3f3a88395f4715d6e935009402fde54.

@dgomezferro Thanks for the report.
